version: "3.8"
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - data
    command: redis-server --loglevel warning
networks:
  data:
    external: true
